"""Seed data for products. category_name_id is only for the loader; MongoDB stores category_id."""

PRODUCTS = [
    # Lácteos y huevos
    {
        "name": "Whole Milk",
        "description": "Whole cow's milk",
        "aliases": ["milk"],
        "category_name_id": "dairy",
        "measurement_types": ["volume", "culinary_volume"],
        "allowed_units": ["ml", "l", "cup", "tbsp"],
        "default_unit": "ml",
        "active": True,
    },
    {
        "name": "Natural Yogurt",
        "description": "Plain unsweetened yogurt",
        "aliases": ["plain yogurt", "yogurt"],
        "category_name_id": "dairy",
        "measurement_types": ["mass", "volume", "culinary_volume"],
        "allowed_units": ["g", "kg", "ml", "cup", "tbsp"],
        "default_unit": "g",
        "active": True,
    },
    {
        "name": "Greek Yogurt",
        "description": "Thick Greek-style yogurt",
        "aliases": ["greek yoghurt"],
        "category_name_id": "dairy",
        "measurement_types": ["mass", "culinary_volume"],
        "allowed_units": ["g", "kg", "cup", "tbsp"],
        "default_unit": "g",
        "active": True,
    },
    {
        "name": "Butter",
        "description": "Dairy butter",
        "aliases": [],
        "category_name_id": "dairy",
        "measurement_types": ["mass", "culinary_volume"],
        "allowed_units": ["g", "kg", "tbsp"],
        "default_unit": "g",
        "active": True,
    },
    {
        "name": "Egg",
        "description": "Chicken egg",
        "aliases": ["chicken egg"],
        "category_name_id": "eggs",
        "measurement_types": ["count", "mass"],
        "allowed_units": ["unit", "half_dozen", "dozen", "yolk", "white", "g"],
        "default_unit": "unit",
        "active": True,
    },
    # Aceites, vinagres y líquidos
    {
        "name": "Olive Oil",
        "description": "Olive oil for cooking and seasoning",
        "aliases": [],
        "category_name_id": "oils_fats",
        "measurement_types": ["volume", "culinary_volume"],
        "allowed_units": ["ml", "l", "tsp", "tbsp", "cup"],
        "default_unit": "ml",
        "active": True,
    },
    {
        "name": "Sunflower Oil",
        "description": "Sunflower cooking oil",
        "aliases": [],
        "category_name_id": "oils_fats",
        "measurement_types": ["volume", "culinary_volume"],
        "allowed_units": ["ml", "l", "tsp", "tbsp", "cup"],
        "default_unit": "ml",
        "active": True,
    },
    {
        "name": "White Vinegar",
        "description": "White cooking vinegar",
        "aliases": ["vinegar"],
        "category_name_id": "condiments_sauces",
        "measurement_types": ["volume", "culinary_volume"],
        "allowed_units": ["ml", "l", "tsp", "tbsp", "cup"],
        "default_unit": "ml",
        "active": True,
    },
    {
        "name": "Apple Cider Vinegar",
        "description": "Apple cider vinegar",
        "aliases": [],
        "category_name_id": "condiments_sauces",
        "measurement_types": ["volume", "culinary_volume"],
        "allowed_units": ["ml", "tsp", "tbsp", "cup"],
        "default_unit": "ml",
        "active": True,
    },
    {
        "name": "Water",
        "description": "Water used for cooking",
        "aliases": [],
        "category_name_id": "water_cooking_liquids",
        "measurement_types": ["volume", "culinary_volume"],
        "allowed_units": ["ml", "l", "cup", "tbsp"],
        "default_unit": "ml",
        "active": True,
    },
    # Harinas, cereales y legumbres
    {
        "name": "Wheat Flour 000",
        "description": "Refined wheat flour",
        "aliases": ["flour"],
        "category_name_id": "flours_starches",
        "measurement_types": ["mass", "culinary_volume"],
        "allowed_units": ["g", "kg", "cup", "tbsp"],
        "default_unit": "g",
        "active": True,
    },
    {
        "name": "Cornstarch",
        "description": "Corn starch",
        "aliases": ["corn starch"],
        "category_name_id": "flours_starches",
        "measurement_types": ["mass", "culinary_volume"],
        "allowed_units": ["g", "kg", "cup", "tbsp"],
        "default_unit": "g",
        "active": True,
    },
    {
        "name": "Rice",
        "description": "Uncooked rice",
        "aliases": [],
        "category_name_id": "grains_cereals",
        "measurement_types": ["mass", "culinary_volume"],
        "allowed_units": ["g", "kg", "cup"],
        "default_unit": "g",
        "active": True,
    },
    {
        "name": "Oats",
        "description": "Rolled oats",
        "aliases": [],
        "category_name_id": "grains_cereals",
        "measurement_types": ["mass", "culinary_volume"],
        "allowed_units": ["g", "kg", "cup", "tbsp"],
        "default_unit": "g",
        "active": True,
    },
    {
        "name": "Lentils",
        "description": "Dry lentils",
        "aliases": [],
        "category_name_id": "legumes",
        "measurement_types": ["mass", "culinary_volume"],
        "allowed_units": ["g", "kg", "cup"],
        "default_unit": "g",
        "active": True,
    },
    # Verduras y frutas
    {
        "name": "Onion",
        "description": "Fresh onion",
        "aliases": [],
        "category_name_id": "vegetables",
        "measurement_types": ["count", "mass"],
        "allowed_units": ["unit", "half_unit", "g", "kg"],
        "default_unit": "unit",
        "active": True,
    },
    {
        "name": "Garlic",
        "description": "Fresh garlic",
        "aliases": [],
        "category_name_id": "vegetables",
        "measurement_types": ["count", "mass"],
        "allowed_units": ["clove", "unit", "g"],
        "default_unit": "clove",
        "active": True,
    },
    {
        "name": "Potato",
        "description": "Fresh potato",
        "aliases": [],
        "category_name_id": "vegetables",
        "measurement_types": ["count", "mass"],
        "allowed_units": ["unit", "half_unit", "g", "kg"],
        "default_unit": "unit",
        "active": True,
    },
    {
        "name": "Carrot",
        "description": "Fresh carrot",
        "aliases": [],
        "category_name_id": "vegetables",
        "measurement_types": ["count", "mass"],
        "allowed_units": ["unit", "half_unit", "g", "kg"],
        "default_unit": "unit",
        "active": True,
    },
    {
        "name": "Tomato",
        "description": "Fresh tomato",
        "aliases": [],
        "category_name_id": "vegetables",
        "measurement_types": ["count", "mass"],
        "allowed_units": ["unit", "half_unit", "g", "kg"],
        "default_unit": "unit",
        "active": True,
    },
    {
        "name": "Parsley",
        "description": "Fresh parsley",
        "aliases": [],
        "category_name_id": "herbs_spices",
        "measurement_types": ["mass", "informal"],
        "allowed_units": ["g", "handful", "tbsp", "to_taste"],
        "default_unit": "g",
        "active": True,
    },
    {
        "name": "Lemon",
        "description": "Fresh lemon",
        "aliases": [],
        "category_name_id": "fruits",
        "measurement_types": ["count", "mass"],
        "allowed_units": ["unit", "half_unit", "g"],
        "default_unit": "unit",
        "active": True,
    },
    {
        "name": "Apple",
        "description": "Fresh apple",
        "aliases": [],
        "category_name_id": "fruits",
        "measurement_types": ["count", "mass"],
        "allowed_units": ["unit", "half_unit", "g", "kg"],
        "default_unit": "unit",
        "active": True,
    },
    # Base culinaria
    {
        "name": "Salt",
        "description": "Cooking salt",
        "aliases": [],
        "category_name_id": "herbs_spices",
        "measurement_types": ["mass", "culinary_volume", "informal"],
        "allowed_units": ["g", "kg", "tsp", "tbsp", "pinch", "to_taste"],
        "default_unit": "g",
        "active": True,
    },
    {
        "name": "Black Pepper",
        "description": "Ground or whole black pepper",
        "aliases": ["pepper"],
        "category_name_id": "herbs_spices",
        "measurement_types": ["mass", "culinary_volume", "informal"],
        "allowed_units": ["g", "tsp", "tbsp", "pinch", "to_taste"],
        "default_unit": "g",
        "active": True,
    },
    {
        "name": "Sugar",
        "description": "White granulated sugar",
        "aliases": [],
        "category_name_id": "sweeteners",
        "measurement_types": ["mass", "culinary_volume"],
        "allowed_units": ["g", "kg", "cup", "tbsp", "tsp"],
        "default_unit": "g",
        "active": True,
    },
    {
        "name": "Honey",
        "description": "Natural honey",
        "aliases": [],
        "category_name_id": "sweeteners",
        "measurement_types": ["mass", "volume", "culinary_volume"],
        "allowed_units": ["g", "ml", "tbsp", "tsp", "cup"],
        "default_unit": "g",
        "active": True,
    },
]
